\section{Console\+Exception\+Event Class Reference}
\label{class_symfony_1_1_component_1_1_console_1_1_event_1_1_console_exception_event}\index{Console\+Exception\+Event@{Console\+Exception\+Event}}
Inheritance diagram for Console\+Exception\+Event\+:\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[height=3.000000cm]{class_symfony_1_1_component_1_1_console_1_1_event_1_1_console_exception_event}
\end{center}
\end{figure}
\subsection*{Public Member Functions}
\begin{DoxyCompactItemize}
\item 
{\bf \+\_\+\+\_\+construct} ({\bf Command} \$command, {\bf Input\+Interface} \$input, {\bf Output\+Interface} \$output,\textbackslash{}Exception \$exception, \$exit\+Code)
\item 
{\bf get\+Exception} ()
\item 
{\bf set\+Exception} (\textbackslash{}Exception \$exception)
\item 
{\bf get\+Exit\+Code} ()
\end{DoxyCompactItemize}
\subsection*{Additional Inherited Members}


\subsection{Detailed Description}
Allows to handle exception thrown in a command.

\begin{DoxyAuthor}{Author}
Fabien Potencier {\tt fabien@symfony.\+com} 
\end{DoxyAuthor}


Definition at line 23 of file Console\+Exception\+Event.\+php.



\subsection{Constructor \& Destructor Documentation}
\index{Symfony\+::\+Component\+::\+Console\+::\+Event\+::\+Console\+Exception\+Event@{Symfony\+::\+Component\+::\+Console\+::\+Event\+::\+Console\+Exception\+Event}!\+\_\+\+\_\+construct@{\+\_\+\+\_\+construct}}
\index{\+\_\+\+\_\+construct@{\+\_\+\+\_\+construct}!Symfony\+::\+Component\+::\+Console\+::\+Event\+::\+Console\+Exception\+Event@{Symfony\+::\+Component\+::\+Console\+::\+Event\+::\+Console\+Exception\+Event}}
\subsubsection[{\+\_\+\+\_\+construct}]{\setlength{\rightskip}{0pt plus 5cm}\+\_\+\+\_\+construct (
\begin{DoxyParamCaption}
\item[{{\bf Command}}]{\$command, }
\item[{{\bf Input\+Interface}}]{\$input, }
\item[{{\bf Output\+Interface}}]{\$output, }
\item[{\textbackslash{}Exception}]{\$exception, }
\item[{}]{\$exit\+Code}
\end{DoxyParamCaption}
)}\label{class_symfony_1_1_component_1_1_console_1_1_event_1_1_console_exception_event_a383436663410388fa97a84198f1909d8}


Definition at line 28 of file Console\+Exception\+Event.\+php.



\subsection{Member Function Documentation}
\index{Symfony\+::\+Component\+::\+Console\+::\+Event\+::\+Console\+Exception\+Event@{Symfony\+::\+Component\+::\+Console\+::\+Event\+::\+Console\+Exception\+Event}!get\+Exception@{get\+Exception}}
\index{get\+Exception@{get\+Exception}!Symfony\+::\+Component\+::\+Console\+::\+Event\+::\+Console\+Exception\+Event@{Symfony\+::\+Component\+::\+Console\+::\+Event\+::\+Console\+Exception\+Event}}
\subsubsection[{get\+Exception}]{\setlength{\rightskip}{0pt plus 5cm}get\+Exception (
\begin{DoxyParamCaption}
{}
\end{DoxyParamCaption}
)}\label{class_symfony_1_1_component_1_1_console_1_1_event_1_1_console_exception_event_a31ec439e56ccf74108b96587373a112c}
Returns the thrown exception.

\begin{DoxyReturn}{Returns}
The thrown exception 
\end{DoxyReturn}


Definition at line 41 of file Console\+Exception\+Event.\+php.

\index{Symfony\+::\+Component\+::\+Console\+::\+Event\+::\+Console\+Exception\+Event@{Symfony\+::\+Component\+::\+Console\+::\+Event\+::\+Console\+Exception\+Event}!get\+Exit\+Code@{get\+Exit\+Code}}
\index{get\+Exit\+Code@{get\+Exit\+Code}!Symfony\+::\+Component\+::\+Console\+::\+Event\+::\+Console\+Exception\+Event@{Symfony\+::\+Component\+::\+Console\+::\+Event\+::\+Console\+Exception\+Event}}
\subsubsection[{get\+Exit\+Code}]{\setlength{\rightskip}{0pt plus 5cm}get\+Exit\+Code (
\begin{DoxyParamCaption}
{}
\end{DoxyParamCaption}
)}\label{class_symfony_1_1_component_1_1_console_1_1_event_1_1_console_exception_event_a946e1b288785f27fbc87ae08742b16c3}
Gets the exit code.

\begin{DoxyReturn}{Returns}
int The command exit code 
\end{DoxyReturn}


Definition at line 63 of file Console\+Exception\+Event.\+php.

\index{Symfony\+::\+Component\+::\+Console\+::\+Event\+::\+Console\+Exception\+Event@{Symfony\+::\+Component\+::\+Console\+::\+Event\+::\+Console\+Exception\+Event}!set\+Exception@{set\+Exception}}
\index{set\+Exception@{set\+Exception}!Symfony\+::\+Component\+::\+Console\+::\+Event\+::\+Console\+Exception\+Event@{Symfony\+::\+Component\+::\+Console\+::\+Event\+::\+Console\+Exception\+Event}}
\subsubsection[{set\+Exception}]{\setlength{\rightskip}{0pt plus 5cm}set\+Exception (
\begin{DoxyParamCaption}
\item[{\textbackslash{}Exception}]{\$exception}
\end{DoxyParamCaption}
)}\label{class_symfony_1_1_component_1_1_console_1_1_event_1_1_console_exception_event_a97d09359d3f5e0d25e9ec87e5ca7db61}
Replaces the thrown exception.

This exception will be thrown if no response is set in the event.


\begin{DoxyParams}[1]{Parameters}
\textbackslash{}\+Exception & {\em \$exception} & The thrown exception \\
\hline
\end{DoxyParams}


Definition at line 53 of file Console\+Exception\+Event.\+php.



The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
vendor/symfony/console/\+Symfony/\+Component/\+Console/\+Event/{\bf Console\+Exception\+Event.\+php}\end{DoxyCompactItemize}
