\section{Get\+Response\+For\+Exception\+Event Class Reference}
\label{class_symfony_1_1_component_1_1_http_kernel_1_1_event_1_1_get_response_for_exception_event}\index{Get\+Response\+For\+Exception\+Event@{Get\+Response\+For\+Exception\+Event}}
Inheritance diagram for Get\+Response\+For\+Exception\+Event\+:\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[height=4.000000cm]{class_symfony_1_1_component_1_1_http_kernel_1_1_event_1_1_get_response_for_exception_event}
\end{center}
\end{figure}
\subsection*{Public Member Functions}
\begin{DoxyCompactItemize}
\item 
{\bf \+\_\+\+\_\+construct} ({\bf Http\+Kernel\+Interface} \$kernel, {\bf Request} \$request, \$request\+Type,\textbackslash{}Exception \${\bf e})
\item 
{\bf get\+Exception} ()
\item 
{\bf set\+Exception} (\textbackslash{}Exception \$exception)
\end{DoxyCompactItemize}


\subsection{Detailed Description}
Allows to create a response for a thrown exception.

Call \doxyref{set\+Response()}{p.}{class_symfony_1_1_component_1_1_http_kernel_1_1_event_1_1_get_response_event_ad90ad569340a3c13f0e71fe8f92427ee} to set the response that will be returned for the current request. The propagation of this event is stopped as soon as a response is set.

You can also call \doxyref{set\+Exception()}{p.}{class_symfony_1_1_component_1_1_http_kernel_1_1_event_1_1_get_response_for_exception_event_a97d09359d3f5e0d25e9ec87e5ca7db61} to replace the thrown exception. This exception will be thrown if no response is set during processing of this event.

\begin{DoxyAuthor}{Author}
Bernhard Schussek {\tt bschussek@gmail.\+com}
\end{DoxyAuthor}


Definition at line 32 of file Get\+Response\+For\+Exception\+Event.\+php.



\subsection{Constructor \& Destructor Documentation}
\index{Symfony\+::\+Component\+::\+Http\+Kernel\+::\+Event\+::\+Get\+Response\+For\+Exception\+Event@{Symfony\+::\+Component\+::\+Http\+Kernel\+::\+Event\+::\+Get\+Response\+For\+Exception\+Event}!\+\_\+\+\_\+construct@{\+\_\+\+\_\+construct}}
\index{\+\_\+\+\_\+construct@{\+\_\+\+\_\+construct}!Symfony\+::\+Component\+::\+Http\+Kernel\+::\+Event\+::\+Get\+Response\+For\+Exception\+Event@{Symfony\+::\+Component\+::\+Http\+Kernel\+::\+Event\+::\+Get\+Response\+For\+Exception\+Event}}
\subsubsection[{\+\_\+\+\_\+construct}]{\setlength{\rightskip}{0pt plus 5cm}\+\_\+\+\_\+construct (
\begin{DoxyParamCaption}
\item[{{\bf Http\+Kernel\+Interface}}]{\$kernel, }
\item[{{\bf Request}}]{\$request, }
\item[{}]{\$request\+Type, }
\item[{\textbackslash{}Exception}]{\$e}
\end{DoxyParamCaption}
)}\label{class_symfony_1_1_component_1_1_http_kernel_1_1_event_1_1_get_response_for_exception_event_afe1161f676ae4f0d4109deb218994724}


Definition at line 41 of file Get\+Response\+For\+Exception\+Event.\+php.



\subsection{Member Function Documentation}
\index{Symfony\+::\+Component\+::\+Http\+Kernel\+::\+Event\+::\+Get\+Response\+For\+Exception\+Event@{Symfony\+::\+Component\+::\+Http\+Kernel\+::\+Event\+::\+Get\+Response\+For\+Exception\+Event}!get\+Exception@{get\+Exception}}
\index{get\+Exception@{get\+Exception}!Symfony\+::\+Component\+::\+Http\+Kernel\+::\+Event\+::\+Get\+Response\+For\+Exception\+Event@{Symfony\+::\+Component\+::\+Http\+Kernel\+::\+Event\+::\+Get\+Response\+For\+Exception\+Event}}
\subsubsection[{get\+Exception}]{\setlength{\rightskip}{0pt plus 5cm}get\+Exception (
\begin{DoxyParamCaption}
{}
\end{DoxyParamCaption}
)}\label{class_symfony_1_1_component_1_1_http_kernel_1_1_event_1_1_get_response_for_exception_event_a31ec439e56ccf74108b96587373a112c}
Returns the thrown exception.

\begin{DoxyReturn}{Returns}
The thrown exception
\end{DoxyReturn}


Definition at line 55 of file Get\+Response\+For\+Exception\+Event.\+php.

\index{Symfony\+::\+Component\+::\+Http\+Kernel\+::\+Event\+::\+Get\+Response\+For\+Exception\+Event@{Symfony\+::\+Component\+::\+Http\+Kernel\+::\+Event\+::\+Get\+Response\+For\+Exception\+Event}!set\+Exception@{set\+Exception}}
\index{set\+Exception@{set\+Exception}!Symfony\+::\+Component\+::\+Http\+Kernel\+::\+Event\+::\+Get\+Response\+For\+Exception\+Event@{Symfony\+::\+Component\+::\+Http\+Kernel\+::\+Event\+::\+Get\+Response\+For\+Exception\+Event}}
\subsubsection[{set\+Exception}]{\setlength{\rightskip}{0pt plus 5cm}set\+Exception (
\begin{DoxyParamCaption}
\item[{\textbackslash{}Exception}]{\$exception}
\end{DoxyParamCaption}
)}\label{class_symfony_1_1_component_1_1_http_kernel_1_1_event_1_1_get_response_for_exception_event_a97d09359d3f5e0d25e9ec87e5ca7db61}
Replaces the thrown exception.

This exception will be thrown if no response is set in the event.


\begin{DoxyParams}[1]{Parameters}
\textbackslash{}\+Exception & {\em \$exception} & The thrown exception\\
\hline
\end{DoxyParams}


Definition at line 69 of file Get\+Response\+For\+Exception\+Event.\+php.



The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
vendor/symfony/http-\/kernel/\+Symfony/\+Component/\+Http\+Kernel/\+Event/{\bf Get\+Response\+For\+Exception\+Event.\+php}\end{DoxyCompactItemize}
